name: Sync-Airflow-Image-to-ACR

on:
  workflow_dispatch: # Allows manual triggering from GitHub Actions UI

jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Alibaba Cloud ACR
      uses: docker/login-action@v2.2.0
      with:
        registry: ${{ secrets.ACR_REGISTRY_ADDRESS }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        logout: false

    - name: Debug - Print ACR Secrets
      run: |
        echo "ACR_REGISTRY_ADDRESS: ${{ secrets.ACR_REGISTRY_ADDRESS }}"
        echo "ACR_NAMESPACE: ${{ secrets.ACR_NAMESPACE }}"

    - name: Use Skopeo Tools Sync Image to ACR
      run: |
        #!/usr/bin/env bash
        REGISTRY_ADDRESS="${{ secrets.ACR_REGISTRY_ADDRESS }}"
        NAMESPACE="${{ secrets.ACR_NAMESPACE }}"
        IMAGE_NAME="apache-airflow"
        TAG="latest"
        DESTINATION="docker://${REGISTRY_ADDRESS}/${NAMESPACE}/${IMAGE_NAME}:${TAG}"

        echo "Skopeo Copy Command:"
        echo "skopeo copy docker://docker.io/apache/airflow:${TAG} ${DESTINATION}"

        skopeo copy docker://docker.io/apache/airflow:${TAG} "${DESTINATION}"
